"""empty message

Revision ID: 213628a0291a
Revises: a3bb13dacff8
Create Date: 2020-05-20 08:56:31.455194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213628a0291a'
down_revision = 'a3bb13dacff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Posts', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    # ### end Alembic commands ###
